[2016-11-20 16:31:27,952] [INFO] [base._load_session] -> No session loaded
[2016-11-20 16:31:27,965] [INFO] [graph.hash] -> hash of template HTTP_GET_MONKEY_0 is 4168102103642212340
[2016-11-20 16:31:27,969] [INFO] [graph.hash] -> hash of model is -8069957684332539954
[2016-11-20 16:31:27,972] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: WebInterface listening on 0.0.0.0:26000
                 Log: ./kittylogs/kitty_20161120-163127.log

                 Total possible mutation count: 39
                 Fuzzing the mutation range: 0 to 38
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2016-11-20 16:31:27,979] [INFO] [base.start] -> Performing environment test
[2016-11-20 16:31:27,996] [INFO] [base._test_info] -> Current test: -1
[2016-11-20 16:31:27,998] [INFO] [server.transmit] -> request(28): 474554202f696e6465782e68746d6c20485454502f312e310d0a0d0a
[2016-11-20 16:31:28,514] [INFO] [server._start] -> should keep running? True
[2016-11-20 16:31:28,536] [ERROR] [tcp.pre_test] -> Error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/katnip/targets/tcp.py", line 57, in pre_test
    sock.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[2016-11-20 16:31:28,540] [ERROR] [tcp.pre_test] -> Failed to connect to target server, retrying...
